baseURL = "/"
languageCode = "en-us"
title = "Example Lekh Site"
theme = "lekh"
relativeURLs = true

[params]
Name = "Rahul Tiwari"
Email = "jprrahultiwari@gmail.com"
About = "Software Engineer, FOSS fan and a systems enthusiast."
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = "https://rtiwari.goatcounter.com/count"

[[params.profiles]]
name = "GitHub"
url = "https://github.com/ba11b0y"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/ba11b0y"

[[params.profiles]]
name = "Goodreads"
url = "https://www.goodreads.com/user/show/91520565-rahul-tiwari"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ba11b0y/"
